/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2023 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>

#include "GPIO_Interface.h"
#include "SysTick_Interface.h"
#include "LEDMatrix_Interface.h"
#include <EXTI_Interface.h>
#include <NVIC_Interface.h>
#include <RCC_Interface.h>


int main(void)
{


	//MSTK_vInit();
	LEDMTX_vInit();

//	RCC_AHB1EnableCLK(GPIOAEN);
//	RCC_AHB1EnableCLK(GPIOBEN);
//	RCC_APB2EnableCLK(SYSCFGEN);


	MGPIO_vSetPinType(PORTA,PIN8,OUTPUT);


	MGPIO_vSetOutputPinValueBSR(PORTA,PIN8,SET);


	uint8_t smily[8]={255, 219, 219, 127, 189, 195, 255, 255};

	/* Loop forever */
	for(;;)
	{
		LEDMTX_vDisplayFrame(smily,1000);
//		MGPIO_vSetOutputPinValueBSR(PORTA,PIN8,SET);
//		MSTK_vSetBusyWait(2000000);
//
//		MGPIO_vSetOutputPinValueBSR(PORTA,PIN8,RESET);
//		MSTK_vSetBusyWait(2000000);

	}
}
