/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2023 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include <stdio.h>
#include "GPIO_Interface.h"
#include "SysTick_Interface.h"
#include "RCC_Interface.h"

#include "Segment.h"

#include "Kernel_Interface.h"
uint8_t number=0;
void Task_Increamental()
{
	number ++;
	if (number == 100)
	{
		number=0;
	}
}

void Task_Transversal()
{
	static uint8_t SSD_digit=0;
	if(SSD_digit == units )
	{
		SSD_digit = tens;
	}
	else
	{
		SSD_digit = units;
	}
	SSD_Print_MLX(number, SSD_digit);
}
void Task_print()
{

	//Print_NOMLX(number++);
	static uint8_t SSD_digit=0;
	if(SSD_digit == 0 )
	{
		MGPIO_vSetOutputPinValueBSR(PORTA,PIN8,SET);

		SSD_digit = 1;
	}
	else
	{
		MGPIO_vSetOutputPinValueBSR(PORTA,PIN8,RESET);
		SSD_digit = 0;
	}



}

int main(void)
{
    /* Loop forever */

	 MSTK_vInit();
	 SSD_Init();
	 Kernel_vInit(20000); // tick time = 10 MS

	 Kernel_vCreateTask(0,Task_Transversal,1,0);
	 Kernel_vCreateTask(1,Task_Increamental,100,1);

	 Kernel_vCreateTask(2,Task_print,100,1);


//


	for(;;)
	{

	}
}
