/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2023 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include "RCC_Interface.h"
#include "GPIO_Interface.h"
#include "EXTI_Interface.h"
#include "NVIC_Interface.h"


void myfunc()
{

	MGPIO_vSetOutputPinValueBSR(PORTA,PIN7,SET);
	MGPIO_vSetOutputPinValueBSR(PORTB,PIN7,SET);
}

int main(void)
{
	RCC_AHB1EnableCLK(GPIOAEN);
	RCC_AHB1EnableCLK(GPIOBEN);
	RCC_APB2EnableCLK(SYSCFGEN);


	MGPIO_vSetPinType(PORTA,PIN7,OUTPUT);
	MGPIO_vSetPinType(PORTB,PIN7,OUTPUT);


	MEXTI_vSetInterruptMask(EXTI_LINE_0,EXTI_NotMasked);
	MEXTI_vSetRisingTrigger(EXTI_LINE_0);
	MEXTI_vSetCallBack(EXTI_LINE_0,myfunc);
	MEXTI_vSetSoftwareTrigger(EXTI_LINE_0);


	NVIC_vSetInterruptEnable(NVIC_IEXTI0);


	while (1)
	{

		//	for (int x=0 ;x<=99;x++)
		//	{
		//
		//		if(x==100)
		//		{
		//			x=0;
		//		}
		//		Print_MLX(x);
		//	    for(int i = 0; i < 1000000; i++); // Delay
		//
		//	}
		/* Loop forever */

	}
}
