/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2023 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
// delay
/*
 * busy wait
 * SYSTICK
 * OS Delay -> Multi-tasking
 * executes another tasks during it
 * */
void Task_LED1(void* pvParameters)
{
	while(1)
	{
		TOGGLE_BIT(REG,BIT) ;
		/*OS Delay*/

	}
}
void Task_LED2(void* pvParameters)
{
	while(1)
	{

	}

}
void Task_LED3(void* pvParameters)
{
	while(1)
	{

	}

}

int main(void)
{
    /* Loop forever */
	for(;;);
}
